# Generated by Django 2.0.5 on 2018-07-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=500)),
                ('predictor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(height_field=350, upload_to='')),
                ('link', models.TextField()),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36)),
                ('email_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='boldstatements.User'),
        ),
    ]
