# Generated by Django 2.0.5 on 2018-07-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='image',
            field=models.ImageField(blank=True, height_field=350, upload_to=''),
        ),
        migrations.AlterField(
            model_name='statement',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='boldstatements.User'),
        ),
    ]
