# Generated by Django 2.0.5 on 2018-07-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0002_auto_20180706_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='boldstatements.User'),
        ),
    ]
