# Generated by Django 2.0.5 on 2018-07-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0003_auto_20180706_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='image',
            field=models.ImageField(blank=True, height_field=350, upload_to='media/images'),
        ),
    ]
