# Generated by Django 2.0.5 on 2018-07-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0004_auto_20180706_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
