# Generated by Django 2.0.5 on 2018-07-09 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boldstatements', '0007_auto_20180708_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
