# Generated by Django 2.0.5 on 2018-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0008_statement_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False')], max_length=2),
        ),
        migrations.AddField(
            model_name='statement',
            name='confirmation_source',
            field=models.TextField(blank=True),
        ),
    ]
