# Generated by Django 2.0.5 on 2018-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0009_auto_20180711_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
