# Generated by Django 2.0.5 on 2018-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldstatements', '0011_auto_20180711_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('True!', 'True'), ('False!', 'False')], max_length=6),
        ),
    ]
